# Generated by Django 4.0.1 on 2022-01-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecity',
            old_name='product',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='imagevillage',
            old_name='product',
            new_name='village',
        ),
    ]
