# Generated by Django 4.0.1 on 2022-01-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donation_village_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('image', models.ImageField(upload_to='images/accessories/', verbose_name='الصورة')),
                ('description', models.TextField(verbose_name='النص')),
                ('price', models.PositiveIntegerField(verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('image', models.ImageField(upload_to='images/book/', verbose_name='الصورة')),
                ('description', models.TextField(verbose_name='النص')),
                ('price', models.PositiveIntegerField(verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Embroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('image', models.ImageField(upload_to='images/embroideries/', verbose_name='الصورة')),
                ('description', models.TextField(verbose_name='النص')),
                ('price', models.PositiveIntegerField(verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('image', models.ImageField(upload_to='images/herb/', verbose_name='الصورة')),
                ('description', models.TextField(verbose_name='النص')),
                ('price', models.PositiveIntegerField(verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Olive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('image', models.ImageField(upload_to='images/olive/', verbose_name='الصورة')),
                ('description', models.TextField(verbose_name='النص')),
                ('price', models.PositiveIntegerField(verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='OralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='النص')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
