# Generated by Django 4.0.1 on 2022-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_donationinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='donationinfo',
            name='d_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
