# Generated by Django 4.0.1 on 2022-02-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_donationinfo_id_donationinfo_d_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/city/ActionsPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='ActionsPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/village/ActionsPhotoVillage')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.CreateModel(
            name='AerialPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/city/AerialPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='AerialPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/village/AerialPhotoVillage')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.CreateModel(
            name='CharactersPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/city/CharactersPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='CharactersPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/village/CharactersPhotoVillage')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.CreateModel(
            name='EventsPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/city/EventsPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='EventsPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/village/EventsPhotoVillage')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/city/InstitutionPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/village/InstitutionPhotoVillage')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/city/MiscellaneousPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/village/MiscellaneousPhotoVillage')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.CreateModel(
            name='PanoramicPhotoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='./images/city/PanoramicPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='PanoramicPhotoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='./images/village/PanoramicPhotoCity')),
                ('caption', models.CharField(max_length=255)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.village')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagevillage',
            name='village',
        ),
        migrations.DeleteModel(
            name='ImageCity',
        ),
        migrations.DeleteModel(
            name='ImageVillage',
        ),
    ]
