from django.contrib import admin

from app.models import *

# Register your models here.

admin.site.register(AboutUs)
admin.site.register(City)
admin.site.register(Village)
admin.site.register(Donation)
admin.site.register(OralHistory)
admin.site.register(Embroidery)
admin.site.register(Accessories)
admin.site.register(Book)
admin.site.register(Herb)
admin.site.register(Olive)
admin.site.register(Contact)
admin.site.register(Gallery)
admin.site.register(Training)
admin.site.register(DonationInfo)
admin.site.register(PanoramicPhotoCity)
admin.site.register(AerialPhotoCity)
admin.site.register(ActionsPhotoCity)
admin.site.register(EventsPhotoCity)
admin.site.register(CharactersPhotoCity)
admin.site.register(InstitutionPhotoCity)
admin.site.register(MiscellaneousPhotoCity)
admin.site.register(PanoramicPhotoVillage)
admin.site.register(AerialPhotoVillage)
admin.site.register(ActionsPhotoVillage)
admin.site.register(EventsPhotoVillage)
admin.site.register(CharactersPhotoVillage)
admin.site.register(InstitutionPhotoVillage)
admin.site.register(MiscellaneousPhotoVillage)
admin.site.register(MuseumPhoto)
